version: "3.9"

services:
  app:
    image: evgeniy00/coursework_5:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "5000:80"
    command: flask run -h 0.0.0.0 -p 5000
    restart: always

  nginx:
    image: nginx:1.20
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    restart: always
    depends_on:
      - app
