name: Build and deploy workflow
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: clone code
        uses: action/checkout@v2
      - name: docker build
        run: docker build -t evgeniy00/coursework_5:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push evgeniy00/coursework_5:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  deploy:
    runs-on: ubuntu-latest
    needs: build-and_push
    steps:
      - name: clone code
        uses: action/checkout@v2
      - name: render configs
        run: |
          export REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          mkdir deploy
          envsubst < docker-compose-ci.yaml > deploy/docker-compose.yaml
          envsubst < redis.conf > deploy/redis.conf
          cat nginx.conf > deploy/nginx.conf
      - name: copy files to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "deploy/docker-compose.yaml,deploy/nginx.conf,deploy/redis.conf"
          target: "flask_app_cw_5"
          strip_components: 1
      - name: deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd flask_app_cw_5
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose up -d